collections:
  creators:
    output: true

defaults:
  - scope:
      path: ""
      type: "creators"
    values:
      layout: "creator"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

baseurl: "https://rmtownsend.github.io/jekyll-blog/"

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-include-cache
